### ISSUE TITLE
Style of the wrapper and images

### ISSUE THREAD

**Issue by xx5ko** [devzonetech/reactjs-image-gallery#1]
Great package and thanks for that!
How can we change the styles of the wrapper and the images inside?

**Comment by zdrsoft** [comment]
Hi @xx5ko ,
for now you could use the following props: 
**imageBackgroundColor** - String - Optional. Background color of the image shown in Lightbox. Defaults to black. Handy for transparent images.
**imgClassName** - String - Optional. class for the small preview image.

Also you could use overriding of the current css classes for customization. 

Your request gives me good ideas for development of features for easy customization of the gallery in the next MINOR versions.
